name: CD

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Release
      run: |
        cmake . -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja
    - uses: softprops/action-gh-release@v1
      with:
          files: mtee.exe
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
